FROM ubuntu:latest

# setup skyr node

WORKDIR /skyr
RUN  apt-get update \
  && apt-get install -y wget
RUN wget https://github.com/SkynetResearchProject/Skyrcoin/releases/download/v2.0.1.2/cli_skyrcoin-linux-gnu-x64_v2.0.1.2.tar.gz
RUN tar xf *.tar.gz
RUN rm *.tar.gz
WORKDIR /skyr
COPY docker/skyrcoin.conf .
#RUN ./install-params.sh
#WORKDIR bin
RUN chmod +x ./skyrcoind
ENTRYPOINT ["/skyr/skyrcoind"]
CMD ["-daemon", "--regtest", "-rpcport=27890", "-rpcallowip=0.0.0.0/0", "-rpcuser=rpc", "-rpcpassword=skyrrpc", "-rpcbind=0.0.0.0:27890"]
EXPOSE 27890
